-- Rollback migration 000002

DROP TABLE IF EXISTS memory_patterns;
DROP TABLE IF EXISTS memory_episodes;
DROP TABLE IF EXISTS tasks;

ALTER TABLE skills DROP COLUMN IF EXISTS author;
ALTER TABLE skills DROP COLUMN IF EXISTS downloads;
ALTER TABLE skills DROP COLUMN IF EXISTS rating;
ALTER TABLE skills DROP COLUMN IF EXISTS rating_count;
ALTER TABLE skills DROP COLUMN IF EXISTS permissions;
ALTER TABLE skills DROP COLUMN IF EXISTS is_verified;

ALTER TABLE skill_installs DROP COLUMN IF EXISTS project_id;
ALTER TABLE skill_installs DROP COLUMN IF EXISTS status;
ALTER TABLE skill_installs DROP COLUMN IF EXISTS config;

ALTER TABLE alerts DROP COLUMN IF EXISTS user_id;
ALTER TABLE alerts DROP COLUMN IF EXISTS name;
ALTER TABLE alerts DROP COLUMN IF EXISTS type;
ALTER TABLE alerts DROP COLUMN IF EXISTS condition;
ALTER TABLE alerts DROP COLUMN IF EXISTS channel;
ALTER TABLE alerts DROP COLUMN IF EXISTS is_active;
